name: upload website
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - main
  

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        # normally you would write
        # uses: cypress-io/github-action@v6
        uses: aws-actions/configure-aws-credential@v1
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy static site to S3 bucket
          run:aws s3 sync.s3://wipro --delete
          
